# Generated by Django 4.2.30 on 2026-07-14 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], default='present', max_length=10)),
                ('face_match_confidence', models.FloatField(blank=True, help_text='Face match confidence score (0-100) from mobile app.', null=True)),
                ('capture_photo', models.ImageField(blank=True, help_text='Photo captured during attendance marking.', null=True, upload_to='attendance/captures/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='schools.classroom')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Attendance records',
                'ordering': ['-date', '-check_in_time'],
                'indexes': [models.Index(fields=['school', 'date'], name='attendance__school__66644e_idx'), models.Index(fields=['classroom', 'date'], name='attendance__classro_9ff4f2_idx'), models.Index(fields=['student', 'date'], name='attendance__student_76a8d7_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
